# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/upyog-demo\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:011528278089:key/02f74129-9f7a-4367-ba22-beafc2353987'
